In [2]:
import numpy as np


In [4]:
y_pred=np.array([0.99,0,0,0.99,0,0,0.99,0.99,0.99,0,0.99,0.99,0,0.99,0.99])
y_true=np.array([1,1,0,1,0,0,1,0,0,0,1,1,0,0,1])
y_pred=np.expand_dims(y_pred,axis=-1)
y_true=np.expand_dims(y_true,axis=-1)

(15,)


In [16]:
#x=y_pred
def tp(x,y):
    count=0
    for i in range(x.shape[0]):
        count+=(x[i]==0.99 and y[i]==1)
    return count
def fp(x,y):
    count=0
    for i in range(x.shape[0]):
        count+=(x[i]==0.99 and y[i]==0)
    return count
def fn(x,y):
    count=0
    for i in range(x.shape[0]):
        count+=(x[i]==0 and y[i]==1)
    return count
def tn(x,y):
    count=0
    for i in range(x.shape[0]):
        count+=(x[i]==0 and y[i]==0)
    return count

In [17]:
TP=tp(y_pred,y_true)
TN=tn(y_pred,y_true)
FP=fp(y_pred,y_true)
FN=fn(y_pred,y_true)

In [18]:
confusion_matrix=np.array([[TP,FP],[FN,TN]])

In [19]:
confusion_matrix


array([[6, 3],
       [1, 5]])

In [22]:
def precision(TP,FP,FN,TN):
    return (TP)/(TP+FP)
def accuracy(TP,FP,FN,TN):
    return (TP+TN)/(TP+TN+FP+FN)
def recall(TP,FP,FN,TN):
    return (TP)/(TP+FN)
def F1(pre,rec):
    return (2*pre*rec)/(pre+rec)

In [24]:
print("precison:",precision(TP,FP,FN,TN))
print("recall: ",recall(TP,FP,FN,TN))
print("accuracy:",accuracy(TP,FP,FN,TN))
print("F1:",F1(precision(TP,FP,FN,TN),recall(TP,FP,FN,TN)))

precison: 0.6666666666666666
recall:  0.8571428571428571
accuracy: 0.7333333333333333
F1: 0.75


In [3]:
Y_pred=np.array([0.99,10**-7,10**-7,0.99,10**-7,10**-7,0.99,0.99,0.99,10**-7,0.99,0.99,10**-7,0.99,0.99])
Y_true=np.array([1,1,0,1,0,0,1,0,0,0,1,1,0,0,1])
def bce_loss(y_pred,y_true):
    loss= (1/len(y_pred))*np.sum(-(y_true*np.log(y_pred) - (1-y_true)*np.log(1-y_pred)))
    return loss
print("bce loss :",bce_loss(Y_pred,Y_true))

bce loss : 0.15752577387433558


In [31]:
x=np.array([[4,2,1,3,1,6],[1,8,0,2,4,7]])
x=x.T
print(x)
#x2=np.array([1,8,0,2,4,7])
y=np.array([2,-14,1,-1,-7,-8])
y=np.expand_dims(y,axis=-1)
print(y.shape)
x.shape

[[4 1]
 [2 8]
 [1 0]
 [3 2]
 [1 4]
 [6 7]]
(6, 1)


(6, 2)

In [58]:
def initialise_param(x):
    w=np.random.rand(1,x.shape[1])
    b=np.random.rand(1,1)
    print('w',w.shape)
    return w,b
def forward_path(w,x,b):
    y= np.matmul(w,x.T) + b
    #print('y_predd',y.shape)
    return y
def loss_function(x,y,y_pred):
    loss = np.mean((y_pred-y)**2)
    return loss

def gradient_descent(y,y_pred,x):
    
    #y_pred= np.reshape(y_pred,(y.shape[0],1))
    derv = 2*(y_pred-y)
    #print('derv',derv.shape)
    dw=(derv * x)
    db= np.sum(b)
    return dw,db

def param_update(w,dw,b,db,alpha):
    w= w - (alpha*dw)
    b= b - (alpha*db)
    
    return w,b

In [54]:
w,b= initialise_param(x)
print(w,b)

w (1, 2)
[[0.55935489 0.83235486]] [[0.33497206]]


In [60]:
print(len(x))

6


In [61]:
alpha=10**-2
epochs=10
cost=[]
for i in range(epochs):
    loss=0
    for j in range(len(x)):
        y_pred= forward_path(w,x[j],b)
        #print("y_pred",y_pred.shape)
        loss+=loss_function(x[j],y[j],y_pred)
        dw,db= gradient_descent(y[j],y_pred,x[j])
        w,b=param_update(w,dw,b,db,alpha)
    cost.append(loss/len(x))
print("trained weights ",w,b)


trained weights  [[ 0.99371336 -1.99854946]] [[0.18328219]]


'pwd' is not recognized as an internal or external command,
operable program or batch file.
