In [1]:
import numpy as np
a=np.arange(1,17)
print(a)
a=np.reshape(a,(4,4))
print ("a(4x4):")
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
a(4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [2]:
def swapp(x,y):
    temp=x
    x=y
    y=temp
    return x,y

def transposing(a):
    for i in range(a.shape[0]):
        for j in range(i+1,a.shape[1]):
            a[i][j],a[j][i]=swapp(a[i][j],a[j][i])         
    return a

In [3]:
transposing(a)
a

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [4]:
b=a
for i in range (a.shape[0]):
    for j in range(i+1,a.shape[1]):
        b[i][j]=0
print("the array b is:")
print(b)
print("\nThis matrix is a lower triangular matrix")

transposing(b)
print("\nthe transposed matrix of b is:")
print(b)
print("\nThis matrix is a upper triangular matrix")

the array b is:
[[ 1  0  0  0]
 [ 2  6  0  0]
 [ 3  7 11  0]
 [ 4  8 12 16]]

This matrix is a lower triangular matrix

the transposed matrix of b is:
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]

This matrix is a upper triangular matrix


In [5]:
c=b
transposing(c)
print("the transpose of b^T is :")
print(c)
print("This matrix is again a lower triangular matrix")
print("So when we take a transpose of the transposed matrix(which was upper triangular) we again obtain a lower triangular matrix")

the transpose of b^T is :
[[ 1  0  0  0]
 [ 2  6  0  0]
 [ 3  7 11  0]
 [ 4  8 12 16]]
This matrix is again a lower triangular matrix
So when we take a transpose of the transposed matrix(which was upper triangular) we again obtain a lower triangular matrix
